export const ENEMY_TYPES = {
  skeleton: {
    key: 'skeleton',
    name: 'Skeleton',
    hp: 20,
    speed: 80,
    damage: 8,
    xp: 1,
    knockbackResist: 0,
    color: 0xdcd6d0,
    alpha: 1,
  },
  bat: {
    key: 'bat',
    name: 'Bat',
    hp: 10,
    speed: 150,
    damage: 5,
    xp: 1,
    knockbackResist: 0,
    erraticAmplitude: 0.35,
    color: 0x8f6cb8,
    alpha: 1,
  },
  ghost: {
    key: 'ghost',
    name: 'Ghost',
    hp: 30,
    speed: 60,
    damage: 12,
    xp: 3,
    knockbackResist: 0.5,
    color: 0x9ce8ff,
    alpha: 0.55,
  },
  knight: {
    key: 'knight',
    name: 'Knight',
    hp: 80,
    speed: 50,
    damage: 20,
    xp: 5,
    knockbackResist: 0.8,
    damageMultiplier: 0.5,
    color: 0x7a8799,
    alpha: 1,
  },
  wraith: {
    key: 'wraith',
    name: 'Wraith',
    hp: 40,
    speed: 100,
    damage: 15,
    xp: 4,
    knockbackResist: 0.4,
    teleportCooldownMs: 5000,
    teleportRange: { min: 120, max: 320 },
    color: 0xa7fff2,
    alpha: 0.8,
  },
};

export const ENEMY_SPAWN_TABLES = [
  {
    untilSeconds: 60,
    weights: { skeleton: 1 },
  },
  {
    untilSeconds: 120,
    weights: { skeleton: 0.7, bat: 0.2, ghost: 0.1 },
  },
  {
    untilSeconds: 180,
    weights: { skeleton: 0.4, bat: 0.25, ghost: 0.15, knight: 0.15, wraith: 0.05 },
  },
];
