export const EVOLUTION_CONFIG = [
  {
    id: 'sacredFloodEvolution',
    name: 'Sacred Flood',
    requires: ['holyWater', 'crossBoomerang'],
    evolvedWeaponId: 'sacredFlood',
    description: 'Massive sanctified wave sweeps the battlefield for 50 damage.',
  },
  {
    id: 'infernoLashEvolution',
    name: 'Inferno Lash',
    requires: ['whipChain', 'flamePillar'],
    evolvedWeaponId: 'infernoLash',
    description: 'Whip strikes ignite a blazing trail that scorches all who cross.',
  },
  {
    id: 'purificationNovaEvolution',
    name: 'Purification Nova',
    requires: ['garlicAura', 'silverDagger'],
    evolvedWeaponId: 'purificationNova',
    description: 'Detonates silver light rings that blast enemies away for massive damage.',
  },
  {
    id: 'necroStormEvolution',
    name: 'Necro Storm',
    requires: ['boneShield', 'arcaneOrb'],
    evolvedWeaponId: 'necroStorm',
    description: 'Orbiting skulls carve enemies while firing arcane bolts.',
  },
];

export const EVOLVED_WEAPON_CONFIG = {
  sacredFlood: {
    name: 'Sacred Flood',
    cooldownMs: 3000,
    damage: 50,
    projectileCount: 1,
    area: 96,
    speed: 540,
    durationMs: 1200,
    pierce: 999,
  },
  infernoLash: {
    name: 'Inferno Lash',
    cooldownMs: 1500,
    damage: 60,
    projectileCount: 1,
    area: 130,
    speed: 0,
    durationMs: 150,
    pierce: 999,
    length: 240,
    trailDamage: 20,
    trailTickMs: 250,
    trailDurationMs: 3000,
  },
  purificationNova: {
    name: 'Purification Nova',
    cooldownMs: 5000,
    damage: 80,
    projectileCount: 1,
    area: 400,
    speed: 0,
    durationMs: 850,
    pierce: 999,
    ringWidth: 40,
    knockbackForce: 300,
  },
  necroStorm: {
    name: 'Necro Storm',
    cooldownMs: 2000,
    damage: 20,
    projectileCount: 8,
    area: 200,
    speed: 380,
    durationMs: 0,
    pierce: 999,
    boltDamage: 15,
    boltCooldownMs: 2000,
    minRadius: 100,
    maxRadius: 250,
    skullSize: 18,
  },
};
