export const GAME_CONFIG = {
  world: {
    width: 3200,
    height: 2400,
  },
  player: {
    maxHealth: 100,
    speed: 200,
    invulnerabilityMs: 500,
    pickupRadius: 80,
    startX: 1600,
    startY: 1200,
    healthRegenPerSecond: 0,
  },
  enemies: {
    maxAlive: 200,
    spawn: {
      baseRatePerSecond: 1,
      increasePer10Seconds: 0.1,
      burstMin: 3,
      burstMax: 8,
      burstIntervalMs: 100,
      spawnRadiusPadding: 100,
    },
    scaling: {
      hpPerMinute: 0.05,
      speedPerMinute: 0.02,
      speedCap: 0.5,
      damagePerMinute: 0.03,
      eliteStartSeconds: 900,
      eliteChance: 0.14,
      eliteSizeMultiplier: 2,
      eliteHpMultiplier: 3,
      eliteDamageMultiplier: 1.5,
    },
  },
  bosses: {
    warningSeconds: 3,
    spawnPadding: 120,
    healthBar: {
      width: 420,
      height: 20,
      y: 74,
    },
    contactTickMs: 200,
    schedule: [
      { atSeconds: 120, type: 'boneDragon' },
      { atSeconds: 300, type: 'vampireLord' },
      { atSeconds: 600, type: 'boneDragon' },
      { atSeconds: 900, type: 'vampireLord' },
      { atSeconds: 1200, type: 'deathItself' },
    ],
    types: {
      boneDragon: {
        name: 'BONE DRAGON',
        baseHp: 500,
        hpPerAppearance: 200,
        speed: 40,
        width: 64,
        height: 48,
        color: 0x214a2c,
        fireBreathCooldownMs: 4000,
        fireBreathDamage: 30,
        tailSwipeCooldownMs: 8000,
        tailSwipeDamage: 40,
        tailSwipeRadius: 120,
      },
      vampireLord: {
        name: 'VAMPIRE LORD',
        baseHp: 400,
        hpPerAppearance: 150,
        width: 32,
        height: 48,
        color: 0x5c101c,
        dashSpeed: 260,
        dashDurationMs: 450,
        pauseDurationMs: 2000,
        summonCooldownMs: 6000,
        summonCount: 10,
        lifestealCooldownMs: 7000,
        lifestealDamage: 25,
        lifestealHeal: 25,
      },
      deathItself: {
        name: 'DEATH ITSELF',
        hp: 2000,
        speed: 90,
        speedRampPerSecond: 0.01,
        width: 40,
        height: 56,
        color: 0x1e1e1e,
        contactDamagePerSecond: 50,
        auraRadius: 220,
        auraSpeedBoost: 0.5,
        knockbackImmune: true,
      },
    },
    chest: {
      lifetimeMs: 12000,
      rareHeal: 35,
      rareMoveSpeedMult: 1.06,
    },
  },
  victory: {
    surviveSeconds: 1800,
  },
  xp: {
    pickupRadius: 180,
    magneticSpeed: 280,
  },
};
