export const WEAPON_CONFIG = {
  holyWater: {
    name: 'Holy Water',
    cooldownMs: 3000,
    damage: 10,
    projectileCount: 1,
    area: 80,
    speed: 560,
    durationMs: 2000,
    pierce: 999,
    tickMs: 300,
    throwRadius: 150,
  },
  crossBoomerang: {
    name: 'Cross Boomerang',
    cooldownMs: 2000,
    damage: 20,
    projectileCount: 1,
    area: 16,
    speed: 420,
    durationMs: 1800,
    pierce: 5,
    outboundDistance: 300,
  },
  whipChain: {
    name: 'Whip Chain',
    cooldownMs: 1500,
    damage: 25,
    projectileCount: 1,
    area: 120,
    speed: 0,
    durationMs: 120,
    pierce: 999,
    length: 200,
  },
  flamePillar: {
    name: 'Flame Pillar',
    cooldownMs: 3500,
    damage: 15,
    projectileCount: 1,
    area: 40,
    speed: 0,
    durationMs: 1500,
    pierce: 999,
    tickMs: 500,
    height: 100,
  },
  garlicAura: {
    name: 'Garlic Aura',
    cooldownMs: 1000,
    damage: 8,
    projectileCount: 1,
    area: 100,
    speed: 0,
    durationMs: 0,
    pierce: 999,
    pushbackForce: 50,
  },
  boneShield: {
    name: 'Bone Shield',
    cooldownMs: 1000,
    damage: 12,
    projectileCount: 3,
    area: 120,
    speed: 0,
    durationMs: 0,
    pierce: 999,
    rotationPeriodMs: 3000,
    hitCooldownMs: 500,
    boneSize: 14,
  },
  silverDagger: {
    name: 'Silver Dagger Rain',
    cooldownMs: 4000,
    damage: 18,
    projectileCount: 5,
    area: 24,
    speed: 520,
    durationMs: 0,
    pierce: 999,
    zoneRadius: 150,
    fallHeight: 340,
  },
  arcaneOrb: {
    name: 'Arcane Orb',
    cooldownMs: 5000,
    damage: 8,
    projectileCount: 1,
    area: 38,
    speed: 80,
    durationMs: 9000,
    pierce: 999,
    tickMs: 300,
  },
};

export const PASSIVE_UPGRADES = {
  maxHealth: {
    id: 'maxHealth',
    name: 'Crimson Vitality',
    description: '+20 Max Health',
  },
  moveSpeed: {
    id: 'moveSpeed',
    name: 'Nightstride',
    description: '+10% Movement Speed',
  },
  pickupRadius: {
    id: 'pickupRadius',
    name: 'Soul Magnetism',
    description: '+20 Pickup Radius',
  },
};
